name: service-a
on:
  push:
    branches:
    - main
    paths:
    - 'service-a/**'
    
jobs:
  build_docker_image:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - run: echo "🎉 The job was automatically triggered by a ${{ github.event_name }} event."

