name: service-b
on:
  push:
    branches:
    - main
    paths:
    - 'service-b/**'
    
jobs:
  build_docker_image:
    name: build docker image
    runs-on: ubuntu-latest
    steps:
      - name: Get Short SHA
        id: short-sha
        run: |
          echo "SHORT_SHA=`echo ${GITHUB_SHA} | cut -c1-8`" >> $GITHUB_ENV
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: sekolahlinux
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          file: service-a/Dockerfile
          push: true
          tags: sekolahlinux/atikur:service-b-${{env.SHORT_SHA}}

